config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
  devise_for :users, skip:[:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  scope module: :user do
    root to: 'homes#top'
    resources :menus, only: [:index, :show]
    resources :shops, only: [:index]
    resources :inquiries, only: [:new, :create] do
      collection do
        get :thanks
      end
    end
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"

  }

  namespace :admin do
    get "/" => "shops#index"
    resources :menus, only: [:new, :index, :show, :edit, :create, :update, :destroy]
    resources :genres, only:[:index, :edit, :create, :update, :destroy]
    resources :shops, only: [:new, :edit, :create, :update]
    resources :inquiries, only: [:index, :show, :edit, :create, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :menus
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_one_attached :image

  belongs_to :genre ,optional: true

  def with_tax_price
    (price * 1.1).floor
  end


end

app/models/shop.rb
class Shop < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genre_controller.rb
class Admin::GenreController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genre = Genre.all
      render :index
    end
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genre = Genre.all
      render :index
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < ApplicationController
  before_action :authenticate_admin!
  def new
    @menu = Menu.new
  end

  def index
    @menus = Menu.all
    @genres = Genre.all
    if params[:genre_id].present?
      @genre = Genre.find(params[:genre_id])
      @menus = @genre.menus
    end
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def edit
    @menu = Menu.find(params[:id])
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.save
    redirect_to admin_menu_path(@menu.id)
  end

  def update
    menu = Menu.find(params[:id])
    menu.update(menu_params)
    redirect_to admin_menu_path(menu.id)
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy
    redirect_to admin_menus_path
  end

  private

  def menu_params
    params.require(:menu).permit(:name, :price, :image, :genre_id)
  end


end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @shop = Shop.new
  end

  def index
    @shops = Shop.all
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def create
    @shop = Shop.new(shop_params)
    @shop.save
    redirect_to admin_path
  end

  def update
    @shop = Shop.find(params[:id])
    @shop.update(shop_params)
    redirect_to admin_path
  end

  private

  def shop_params
    params.require(:shop).permit(:address, :post_code, :business_time, :business_day, :holiday, :telephone)
  end


end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/controllers/user/menus_controller.rb
class User::MenusController < ApplicationController
  def index
    @menus = Menu.all
    @genres = Genre.all
    if params[:genre_id].present?
      @genre = Genre.find(params[:genre_id])
      @menus = @genre.menus
    end
  end

  def show
    @menu = Menu.find(params[:id])
  end

end

app/controllers/user/shops_controller.rb
class User::ShopsController < ApplicationController
  def index
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/genre_helper.rb
module Admin::GenreHelper
end

app/helpers/admin/inquiries_helper.rb
module Admin::InquiriesHelper
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/inquiries_helper.rb
module User::InquiriesHelper
end

app/helpers/user/menu_helper.rb
module User::MenuHelper
end

app/views/admin/menus/edit.html.erb
<%= form_with model: @menu, url: admin_menu_path(@menu.id) do |f| %>
  <dl>
    <dt><%= f.label "画像" %></dt>
    <dd><%= f.file_field :image, accept: "image/*" %></dd>
  </dl>
  <dl>
    <dt><%= f.label "商品名" %></dt>
    <dd><%= f.text_field :name %></dd>
  </dl>
  <dl>
    <dt><%= f.label "価格" %></dt>
    <dd><%= f.text_field :price %></dd>
  </dl>
  <dl>
    <dt><%= f.label "ジャンル" %></dt>
    <dd><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %></dd>
  </dl>
  <%= f.submit "変更する" %>
  <%= link_to "削除する", admin_menu_path, method: :delete %>
<% end %>

app/views/admin/menus/index.html.erb
<%= link_to "メニュー追加", new_admin_menu_path %>
<div class="mg_seach">
  <p>ジャンル検索</p>
  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <% if genre.present? == true %>
        <td>
          <%= link_to genre.name, admin_menus_path(genre_id: genre.id), class: "text-secondary" %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</div>

<div class="m_content">
  <h2>メニュー一覧</h2>
  <%= link_to "一覧へ戻る",  admin_menus_path %>
  <div class="m_list">
    <% @menus.each do |menu| %>
      <table class="menu">
        <%= link_to admin_menu_path(menu.id) do %>
          <%= menu.name %>
        <% end %>
        ¥<%= menu.price %>
      </table>
    <% end %>
  </div>
</div>

app/views/admin/menus/new.html.erb
<%= form_with model: @menu, url: admin_menus_path do |f| %>
  <table class="menu_new">
    <tr>
      <td>画像</td>
      <td><%= f.file_field :image, accept: "image/*" %></td>
    </tr>
    <tr>
      <td>商品名</td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td>価格</td>
      <td><%= f.text_field :price %></td>
    </tr>
    <tr>
      <td>ジャンル</td>
      <td><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %></td>
      <%= link_to "ジャンル追加へ", admin_genres_path %>
    </tr>
    <tr>
      <td><%= f.submit "保存" %></td>
    </tr>
  </table>
<% end %>

app/views/admin/menus/show.html.erb
<%= link_to "編集する", edit_admin_menu_path(@menu.id) %>

<% if @menu.image.attached? %>
  <%= image_tag @menu.image, size: "300x300" %>
 <% else %>
  <%= image_tag "no_image", size: "300x300" %>
 <% end %>
<ul class="menu_show">
  <li>
    <p>商品名 <%= @menu.name %></p>
  </li>
  <li>
    <p>価格(税込) ¥<%= @menu.price %>(¥<%= @menu.with_tax_price %>)</p>
  </li>
  <li>
    <p>ジャンル <%= @menu.genre.name %></p>
  </li>
</ul>