config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
  devise_for :users, skip:[:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  scope module: :user do
    root to: 'homes#top'
    resources :menus, only: [:index, :show]
    resources :shops, only: [:index]
    resources :inquiries, only: [:new, :create] do
      collection do
        get :thanks
      end
    end
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"

  }

  namespace :admin do
    get "/" => "shops#index"
    resources :menus, only: [:new, :index, :show, :edit, :create, :update, :destroy]
    resources :genres, only:[:index, :edit, :create, :update, :destroy]
    resources :shops, only: [:new, :edit, :create, :update]
    resources :inquiries, only: [:index, :show, :edit, :create, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :menus
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_one_attached :image

  belongs_to :genre ,optional: true

  def with_tax_price
    (price * 1.1).floor
  end


end

app/models/shop.rb
class Shop < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genre_controller.rb
class Admin::GenreController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genre = Genre.all
      render :index
    end
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/controllers/user/menus_controller.rb
class User::MenusController < ApplicationController
  def index
    @menus = Menu.all
    @genres = Genre.all
    if params[:genre_id].present?
      @genre = Genre.find(params[:genre_id])
      @menus = @genre.menus
    end
  end

  def show
    @menu = Menu.find(params[:id])
  end

end

app/controllers/user/shops_controller.rb
class User::ShopsController < ApplicationController
  def index
  end
end

app/helpers/admin/genre_helper.rb
module Admin::GenreHelper
end

app/helpers/admin/inquiries_helper.rb
module Admin::InquiriesHelper
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/inquiries_helper.rb
module User::InquiriesHelper
end

app/helpers/user/menu_helper.rb
module User::MenuHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <h1 id="main_title">出汁おでん居酒屋為ちゃん家</h1>
      <!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"-->
      <!--                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">-->
      <!--  <span class="navbar-toggler-icon"></span>-->
      <!--</button>-->
       <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <li>
              <%= link_to admin_menus_path do %>
                <i class="fa-solid fa-list-ul"></i>
                メニュー
              <% end %>
            </li>
            <li>
              <%= link_to admin_genres_path do %>
                <i class="fa-solid fa-list-ul"></i>
                ジャンル
              <% end %>
            </li>
            <li>
              <%= link_to "/admin" do %>
                <i class="fa-solid fa-users"></i>
                店舗情報
              <% end %>
            </li>
            <li>
              <%= link_to admin_inquiries_path do %>
                <i class="fa-solid fa-users"></i>
                お問合せ一覧
              <% end %>
            </li>
            <li>
              <%= link_to destroy_admin_session_path, method: :delete do  %>
                <i class="fa-sharp fa-solid fa-arrow-right-from-bracket"></i>
                ログアウト
              <% end %>
            </li>
          <% else %>
            <li><a href="/">HOME</a></li>
            <li>
              <%= link_to menus_path do %>
                メニュー
              <% end %>
            </li>
            <li>
              <%= link_to shops_path do %>
                店舗情報
              <% end %>
            </li>
            <li>
              <%= link_to new_inquiry_path do %>
                お問合せ
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>為ちゃん家</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>-->
    <!--<script type='text/javascript' src="/js/jquery.validate.min.js"></script>-->

    <!--<script type='text/javascript' src="/js/jquery.validate.handler.js"></script>-->

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <% unless current_page?(root_path) %> <%# unlessで現在のページがrootなら呼び出さない %>
      <%= render "layouts/header" %>
    <% end %>

    <span id="back">
      <a href="#">
        <%= image_tag asset_path("arrow.png") %>
      </a>
    </span>
    <%= yield %>
  </body>
</html>